obergeinn/src/Entity/Survey.php
<?php

namespace App\Entity;

use App\Repository\SurveyRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

/**
 * @ORM\Entity(repositoryClass=SurveyRepository::class)
 */
class Survey
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="boolean")
     */
    private $status;

    /**
     * @ORM\OneToOne(targetEntity=Event::class, inversedBy="survey", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $event;

    /**
     * @ORM\OneToMany(targetEntity=SurveyResponses::class, mappedBy="survey", orphanRemoval=true)
     */
    private $survey_responses;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=false)
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $updatedAt;

    public function __construct()
    {
        $this->survey_responses = new ArrayCollection();
        $this->createdAt = new DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getEvent(): ?Event
    {
        return $this->event;
    }

    public function setEvent(Event $event): self
    {
        $this->event = $event;

        return $this;
    }

    /**
     * @return Collection|SurveyResponses[]
     */
    public function getSurveyResponses(): Collection
    {
        return $this->survey_responses;
    }

    public function addSurveyResponse(SurveyResponses $surveyResponse): self
    {
        if (!$this->survey_responses->contains($surveyResponse)) {
            $this->survey_responses[] = $surveyResponse;
            $surveyResponse->setSurvey($this);
        }

        return $this;
    }

    public function removeSurveyResponse(SurveyResponses $surveyResponse): self
    {
        if ($this->survey_responses->removeElement($surveyResponse)) {
            // set the owning side to null (unless already changed)
            if ($surveyResponse->getSurvey() === $this) {
                $surveyResponse->setSurvey(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(?\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}

obergeinn/src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\NotBlank;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('title', null, [
            'label' => 'Titre',
            'trim' => true,
            'row_attr' => [
                'class' => 'event-edit-form-label'
            ],
            'required' => 'required',
            'constraints' => new NotBlank([
                    'message' => 'Merci de saisir un titre pour l\'événement',
            ]),
        ])
        ->add('adress', null, [
            'label' => 'Adresse',
            'trim' => true,
            'row_attr' => [
                'class' => 'event-edit-form-label'
            ],
            'required' => 'required',
            'constraints' => new NotBlank([
                'message' => 'Merci de saisir une adresse',
            ]),
            'help' => 'Format : adresse - code postal - ville',
        ])
        ->add('description', null, [
            'label' => 'Description',
            'trim' => true,
            'row_attr' => [
                'class' => 'event-edit-form-label'
            ],
            'required' => 'required',
            'constraints' => new NotBlank([
                'message' => 'Merci de saisir une description',
            ]),
        ])
        ->add('date', DateTimeType::class, [
            'label' => 'Date',
            'widget'=> 'single_text',
            'input' => 'datetime_immutable',
            'trim' => true,
            'row_attr' => [
                'class' => 'event-edit-form-label'
            ],
        ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

obergeinn/src/Controller/Backoffice/EventController.php
<?php

namespace App\Controller\Backoffice;

use App\Entity\Event;
use App\Form\EventType;
use App\Repository\EventRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
* @Route("/backoffice/evenement", name="backoffice_event_", requirements={"id": "\d+"})
* @IsGranted("ROLE_ADMIN")
*/
class EventController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index(EventRepository $eventRepository): Response
    {
        return $this->render('backoffice/event/index.html.twig', [
            'events' => $eventRepository->findAll(),
        ]);
    }

    /**
     * Page which enable to see the detailed information of an existing event
     * URL : /backoffice/evenement/editer/{id}
     * Route : backoffice_event_edit
     * 
     * @Route("/editer/{id}", name="edit")
     *
     * @return Response
     */
    // Use of param converter in order to display an error 404 if the user id doesn't exist
    public function edit(Event $event, Request $request)
    {
        $form = $this->createForm(EventType::class, $event);

        $form->handleRequest($request);

        // We check that the datas are valid before saving them.
        if ($form->isSubmitted() && $form->isValid()) {

            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', 'L\'événement ' . $event->getTitle() . ' a bien été mis à jour.');

            return $this->redirectToRoute('backoffice_event_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('backoffice/event/edit.html.twig', [
            'event' => $event,
            'eventView' => $form,
        ]);
    }

    /**
     * Page which allow the removal of an account.
     * 
     * URL : /backoffice/evenement/supprimer/{id}
     * Route : backoffice_event_delete
     * 
     * @Route("/supprimer/{id}", name="delete")
     */
    public function delete(Request $request, Event $event): Response
    {
        if ($this->isCsrfTokenValid('delete' . $event->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($event);
            $entityManager->flush();
        }

        $this->addFlash('danger', 'L\'événement ' . $event->getTitle() . ' a bien été supprimé.');

        return $this->redirectToRoute('backoffice_event_index', [], Response::HTTP_SEE_OTHER);
    }
}

obergeinn/src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\EventCreateType;
use App\Entity\Assignation;
use App\Entity\Need;
use App\Form\EventType;
use App\Repository\EventRepository;
use App\Repository\MeasureUnitRepository;
use App\Repository\NeedRepository;
use App\Repository\TypeRepository;
use DateTimeImmutable;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\FormTypeInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/evenement", name="event_")
 * @IsGranted("ROLE_USER")
 */
class EventController extends AbstractController
{
    /**
     * Method allowing the display of the list of an event for a determined user
     * 
     * @Route("/", name="index")
     *
     * @return Response
     */
    public function index(EventRepository $eventRepository): Response
    {
        // Manage the archiving of all the events according to the current date and the event date 
        $eventList = $eventRepository->findAll();

        foreach ($eventList as $event) {

            // Recover current date and event date
            $todayDate = new DateTimeImmutable();
            $eventDate = $event->getDate();

            // To compare it.
            if (isset($eventDate) && $eventDate < $todayDate) {
                if ($event->getStatus() == 0) {
                    //event already archived
                } else {
                    $em = $this->getDoctrine()->getManager();
                    $event->setStatus(0);
                    $em->flush();
                }
            }
        }
        return $this->render('event/index.html.twig', [
            'controller_name' => 'EventController',
        ]);
    }

    /**
     * Method allowing the display of the details of an event
     * 
     * @Route("/details/{id}", name="show", requirements={"id": "\d+"})
     *
     * @param int $id
     * @return void
     */
    public function show(int $id, EventRepository $eventRepository, NeedRepository $needRepository) : Response
    {
        $event = $eventRepository->find($id);

        $userConnected = $this->getUser()->getId();
        $eventOrganizer = $event->getUser()->getId();
        
        $guestList = [];

        foreach ($event->getParticipation() as $value) {
       
            $eventGuest = $value->getUser()->getId();
            array_push($guestList, $eventGuest);
        };

        // If the user who try to access the current page is different to the event organizer or to an event guest, a 403 exception will be thrown
        if ($userConnected != $eventOrganizer) {
            if (in_array($userConnected, $guestList) === false) {
                throw $this->createAccessDeniedException('Vous n\'avez pas les droits pour accèder à cette page');
            }
        };

        $formArray = [];
        
        // If the modal input is not null 
        if ($_POST) {
            foreach ($event->getNeed() as $singleNeed) {

                $formArray[$singleNeed->getId()] = filter_input(INPUT_POST, 'quantity-assignees'.$singleNeed->getId(), FILTER_VALIDATE_INT);
            };
            foreach ($formArray as $needId => $quantity) {
                if ($quantity > 0) {
                    $assignation = new Assignation();
                    $assignation->setQuantity($quantity);
                    $assignation->setUser($this->getUser());
                    $assignation->setNeed($needRepository->find($needId));
                    $entityManager = $this->getDoctrine()->getManager();
                    $entityManager->persist($assignation);
                }
            }
            $entityManager->flush();

            $this->addFlash('success', 'Vos assignations de besoins ont bien été enregistrées');
        }

        // Calculate percent for progress bar of needs
        $totalNeedsQuantity = 0;
        $totalAssignatedNeedsQuantity = 0;
        foreach ($event->getNeeds() as $need) {
            $totalNeedsQuantity += $need->getQuantity();
            foreach ($need->getAssignations() as $assignation) {
                $totalAssignatedNeedsQuantity += $assignation->getQuantity();
            }
        };
        if ($totalNeedsQuantity <= 0) {
            $needsPercent = 0;
        } else {
            $needsPercent = number_format(($totalAssignatedNeedsQuantity*100)/$totalNeedsQuantity,0);
        }



        if (!$event) {
            throw $this->createNotFoundException()("L'événement n'existe pas");
        }
        return $this->render('event/show.html.twig', [
            'event' => $event,
            'needsPercent' => $needsPercent,
        ]);
    }

    /**
     * Method allowing the display of the creation page of an event
     * 
     * @Route("/creer", name="create")
     *
     * @return void
     */
    public function create(Request $request) 
    {
        // 1st step : we will "instance" an empty object
        $event = new Event();

        // 2nd step : we will "instant" the formtype of our event.
        // we link the instance $event with our form
        $form = $this->createForm(EventCreateType::class, $event);
        
        // 4th step : we receive the data submitted by the form
        // which are injected in the object $event
        $form->handleRequest($request);
        $event->setUser($this->getUser());
        $event->setStatus(1);
        // 5th stage : we check if we are in the case of submission of form before saving
        if ($form->isSubmitted() && $form->isValid()) {
            
            // we will save the datas and create the new event.
            $em = $this->getDoctrine()->getManager();
            $em->persist($event);
            // for each informed need into the form, we will save it
            foreach ($form->getData()->getNeed() as $need) {
                $em->persist($need);
            }

            $em->flush();

            // Add a flash message to inform the user of the successing creation
            $this->addFlash('success', 'L\'événement ' . $event->getTitle() . ' a bien été créé. Vous pouvez maintenant prévenir vos invités.' );
            // after the form is submitted We will redirect in the detail of the new event created?
            return $this->redirectToRoute('mailer');

        }

        // 3rd step : templates/event/create.html.twig
        return $this->render('event/create.html.twig', [
            'formView' => $form->createView()
        ]);
    }

    /**
     * Method to edit an event
     * 
     * @Route("/{id}/modifier", name="edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Event $event): Response
    {
        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
           
            $this->getDoctrine()->getManager()->flush();

            // Message flash
            $this->addFlash('success', 'L\'événement ' . $event->getTitle() . ' a bien été mis à jour');

            return $this->redirectToRoute('event_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('event/edit.html.twig', [
            'event' => $event,
            'formView' => $form,
        ]);
    }

     /**
     * 
     * Method allowing user to accept an event invitation
     * 
     * @Route("/details/{id}/accept-participate", name="accept", requirements={"id": "\d+"})
     *
     * @return void
     */
    public function eventParticipationAccept(int $id, EventRepository $eventRepository) 
    {
        $event = $eventRepository->find($id);

        $userConnectedParticipation = $this->getUser()->getParticipation();

        $entityManager = $this->getDoctrine()->getManager();

        foreach ($userConnectedParticipation as $userParticipation) {

            if ($event->getId() === $userParticipation->getEvent()->getId()) {
                if ($userParticipation->getStatus() == false) {
                    $userParticipation->setStatus(true);
                    $entityManager->flush();
                }
            }
        }
        return $this->redirectToRoute('event_show', [
            'id' => $id,
        ]);
    }

    /**
     * 
     * Method allowing user to deny an event invitation
     * 
     * @Route("/details/{id}/refuser", name="deny", requirements={"id": "\d+"})
     *
     * @return void
     */
    public function eventParticipationDeny(int $id, EventRepository $eventRepository) 
    {
        $event = $eventRepository->find($id);
        $em = $this->getDoctrine()->getManager();

        $userConnectedParticipation = $this->getUser()->getParticipation();

        // We remove the user assignations for the current event
        foreach ($this->getUser()->getAssignations() as $assignation) {
            if ($assignation->getNeed()->getEvent() == $event) {
                $em->remove($assignation);
                $em->flush();
            }
        }
        // We remove the user participation for the current event
        foreach ($userConnectedParticipation as $userParticipation) {

            if ($event->getId() === $userParticipation->getEvent()->getId()) {
                $em->remove($userParticipation);
                $em->flush();

                $this->addFlash('warning', 'Vous ne participez plus à l\'événement ' . $event->getTitle() .'.');
            }
        }

        return $this->redirectToRoute('dashboard', [
            'id' => $id,
        ]);
    }

    /**
     * Method dealing the arhiving of an event
     * 
     * @Route("/{id}/archiver", name="archiving")
     *
     * @param integer $id
     * @return Response
     */
    public function archiving(int $id, EventRepository $eventRepository): Response
    {
        $event = $eventRepository->find($id);

obergeinn/templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="container show">
    <button class="button-link d-flex align-self-start ms-4 bg-one rounded p-1">
        <a class="text-decoration-none link color-four" href="{{ path('event_index') }}">Retour</a>
    </button>

        {# Title section #}
        <section class="title">
        {#redirect to eventlist not dashboard #}  
            <h1 class="text-uppercase fw-bold">{{event.title}}</h1>
            <p class="event-details-date fs-4">
            {% if event.date %}
            {# we have create a condition for display the Date of the event if it's defined, else show "ND" for "non définie"#}
            le {{ event.date ? event.date|date('d-M-Y') : 'NC' }} 
            {% else %}
            Date non communiquée
            {% endif %}
            </p>
            <h3 id="by-pseudo"class="fw-bold color-three mb-5">par {{event.user.pseudo}}</h3>          
        </section>
    <div class="event-details-content">
        {# Description section #}
        <section class="description">
            <div>
                <h2>Description</h2>
                <p>{{event.description}}</p>
            </div>
        
        </section>
           
        {# Adress section #}
        <section class="adress">

            <div class="adress-text">
                <h2 class="color-three mt-2">Adresse </h2>
                <p id="adress" class="fs-4 color-four" data-adress="{{event.adress}}">{{event.adress}}</p>
                
            </div>

            <div id="map" class="align-self-center border rounded-bottom"></div>

        </section>

                {# If a survey exists for this event, display the survey #}
                {% if event.survey and event.survey.status == true %}
        {# Survey section #}            
        <section class="survey">
            <div class="mx-auto">
              
                <h2>Sondage</h2>
                <div class="survey-list">

                    {% set dateChoiceNumber = 1 %}
                    {% for responses in event.survey.surveyResponses %}

                        <form action="{{path('survey_answered', {'id': event.id})}}" method="post" class="form-check d-flex flex-column align-items-center fs-4 justify-content-around ps-0">
                            <div>
                                <input class="form-check-input" type="checkbox" value="{{responses.response|date('d-M-Y')}}" id="date{{dateChoiceNumber}}" name="dateChoice{{dateChoiceNumber}}" 

                                {% for choices in responses.surveyChoices %}
                                    {# If the user connected has already answered the survey #}
                                    {% if choices.user == app.user %}
                                    {# Checked the checkboxes#}
                                        checked
                                    {% endif %}
                                {% endfor %}
                                >
                                <label class="form-check-label" for="date{{dateChoiceNumber}}">
                                    {{responses.response|date('d-M-Y')}}
                                </label>
                            </div>
                                {% set dateChoiceNumber = dateChoiceNumber + 1 %}
                    {% endfor %}
                                <input type="submit" value="Valider" class="button_inscription mt-2 mb-2" 

                                {% for responses in event.survey.surveyResponses %}
                                    {% for choices in responses.surveyChoices %}
                                        {# If the user connected has already answered the survey #}
                                        {% if choices.user == app.user %}
                                            {# Hide the submit button #}
                                            hidden
                                        {% endif %}
                                    {% endfor %}
                                {% endfor %}
                                >
                            </form>    
            </div>
        </section> 
                {% endif %}    

        {# Need section #}
        <section class="need-section">
            <div>
                <!-- Button trigger modal -->
                <button type="button" class="btn btn-lg button-needs" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                Liste des besoins
                </button>
                            {# {{dump(event.user, app.user)}} #}

                <!-- Modal -->
                <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title fw-bold" id="staticBackdropLabel">Liste des besoins</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <form action="" method="post" class="modal-body">

                            {# For every needs of the current event #}
                            {% for need in event.need %}

                            <div class="form-check d-flex fs-4">
                                <input class="form-check-input-modal me-2" type="checkbox" value="" id="flexCheck{{need.id}}"
                                
                                {# We retrieve all quantities which are already assigned #}
                                {% set totalAssignations = 0 %}
                                {% for assignation in need.assignations %}
                                    {# We add them up #}
                                    {% set totalAssignations = totalAssignations + assignation.quantity %}
                                    {# If the difference between the quantity needed and the quantity already assigned is null or negative #}
                                    {% if need.quantity - totalAssignations <= 0 %}
                                    {# disabled the checkbox to avoid another assignation #}
                                        {{"disabled"}}
                                    {% endif %}
                                {% endfor %}
                                
                                >
                                <label class="form-check-label" for="flexCheck{{need.id}}">

                                {{need.quantity}} {{need.measureUnit.unit}} {{need.name}}                        
                                
                                </label>
                                <input class="ms-2 fs-6 checkbox-need" type="number" name="quantity-assignees{{need.id}}" hidden>
                            </div>
                            {% endfor %}

                        <div class="modal-footer">
                            <p class="text-center color-five"
                            {% for participation in app.user.participation %}
                                {% if (participation.event == event and (participation.status == true)) %}
                                    hidden
                                    {% elseif ( event.user == app.user) %}
                                    hidden
                                {% endif %}
                            {% endfor %}
                                    ><i class="bi bi-exclamation-triangle-fill"></i> Tu ne peux pas t'assigner de besoins si tu ne confirmes pas ta présence à l'événement.</p>
                                    <button type="button" class="btn button-close" data-bs-dismiss="modal">Fermer</button>
                                    <input type="submit" class="btn button-validate button-validate-need-assignees"
                                    {% for participation in app.user.participation %}
                                {% if participation.event == event and participation.status == false %}
                                    hidden
                                {% endif %}
                            {% endfor %}></input>
                                
                                            
                        </div>
                        </form>
                        <div class="ms-4">
                            <h5 class="fw-bold">Ce que vous devez apporter</h5>
                            {% for need in event.need %}
                                {% for assignation in app.user.assignations %}
                                    {% if need.id == assignation.need.id %}
                                        <ul>
                                        <li>{{assignation.quantity}} {{assignation.need.measureUnit.unit}} {{assignation.need.name}}</li>
                                        </ul>
                                    {% endif %}
                                {% endfor %}
                            {% endfor %}
                        </div>
                        <div class="ms-4">
                            <h5 class="fw-bold">Qui amène quoi?</h5>
                            {% for need in event.need %}
                                {% for assignation in need.assignations %}
                                <ul>
                                    <li> <em class="fw-bold color-two">{{assignation.user.pseudo}} </em> apporte {{assignation.quantity}} {{assignation.need.measureUnit.unit}} {{assignation.need.name}} </p>
                                </ul>
                                {% endfor %}
                            {% endfor %}
                        </div> 
                        </div>
                    </div>
                </div>
                <div class="progress">
                    <div class="progress-bar" role="progressbar" style="width: {{needsPercent}}%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
                    {{needsPercent}}%
                    </div>
                </div>
            </div>
        </section>

        {# Guest section #}
        <section class="guest">
            <div>
                <h2>Invités</h2>

                <div class="guest-list">

                {% for participation in event.participation %}
                    {% if participation.status == true %}
                        <div>
                            {# If the user have no image for his avatar, displayed a generic image #}
                            {% if participation.user.image %}
                                <img alt="icon" src="{{ asset('uploads/' ~ participation.user.image)}}" class="rounded-circle" >
                            {% else %}
                                <img alt="icon" src="{{ asset('assets/images/user-icon.png')}}">
                            {% endif %}
                            <p>{{participation.user.pseudo}}</p>
                        </div>
                        {# If the connected user is the event organizer, display the inactive guests too #}
                    {% elseif participation.status == false and app.user == event.user %}
                        <div>
                            {# If the user have no image for his avatar, displayed a generic image #}
                            {% if participation.user.image %}
                                <img alt="icon" src="{{ asset('uploads/' ~ participation.user.image)}}" class="rounded-circle" >
                            {% else %}
                                <img alt="icon" src="{{ asset('assets/images/user-icon.png')}}">
                            {% endif %}
                            <p><i class="bi bi-x-lg color-five"></i>{{participation.user.pseudo}}</p>
                        </div>
                    {% endif %}              
                    
                {% endfor %}
              
                </div>
            </div>
        </section>

    </div>
        {# Participation section #}
        <section class="participation">

            {# Pour chaque participation de l'utilisateur connecté #}
            {% for participation in app.user.participation %}
            
                {# On vérifie si l'event de la participation correspond à l'event en cours #}
                {% if participation.event == event and participation.status == false %}

                        <a href="{{path('event_accept', {'id': event.id})}}" onclick="return confirm('Es-tu sûr de participer à cet évènement ?');" class="participation-accept" title= "Accepter l'invitation"> <i class="bi bi-check-circle-fill"></i></a>

                        <a href="{{path('event_deny', {'id': event.id})}}" onclick="return confirm('Es-tu sûr de ne pas participer à cet évènement ?');" class="participation-deny" title="Refuser l'invitation"><i class="bi bi-x-circle-fill"></i></a>

                {% elseif participation.event == event and participation.status == true %}
                        <a href="{{path('event_deny', {'id': event.id})}}" onclick="return confirm('Es-tu sûr de ne pas participer à cet évènement ?');" class="participation-deny" title="Je ne participe plus"><i class="bi bi-x-circle-fill"></i></a>
                    
                {% endif %}
            {% endfor %} 
        </section>
</div>
{% endblock %}